### PR TITLE
Add support for ARMv6

### PR DESCRIPTION
**Pull request by jannickfahlbusch**
This adds support for ARMv6 devices like the Raspberry Pi.

### CODE REVIEW

**Comment by jannickfahlbusch** [comment]
Ping @klingtnet 

Are you planning to merge this? If you do so, if would check if I can resolve te conflicts.

**Comment by klingtnet** [comment]
Are you sure that the build supports ARMv6? I can only find builds for ARMv7 on [caddy's download page](https://caddyserver.com/download).

**Comment by jannickfahlbusch** [comment]
Okay, you may recieve double comments or something. I have massive problems resolving GitHubs domains....

---

You need to add `arm=6` to the download URL.

Sadly this is not documented anywhere, but Matt Holt wrote this several
times in issues regarding support for the RaspberryPi.

Sources: 
- https://github.com/mholt/caddy/issues/119#issuecomment-227790862
- https://forum.caddyserver.com/t/caddy-0-9-for-first-raspberry-pi/386/2

**Comment by klingtnet** [comment]
Thank you for your efforts, I've added armv6h support in [5e50d3e](https://github.com/klingtnet/caddy-AUR/commit/5e50d3e50eb489b4502df0e599d1b70a66d160ef).

**Comment by jannickfahlbusch** [comment]
You need to add "arm=6" to the download URL.

Sadly this is not documented anywhere, butt Matt Holt wrote this several
times in issues regarding support for the RaspberryPi.

I can't open GitHub at the moment because of the DDoS against their
DNS-provider, so I provide sources later.

**Comment by jannickfahlbusch** [comment]
Found a link to the Caddy forum:
https://forum.caddyserver.com/t/caddy-0-9-for-first-raspberry-pi/386/2

**Comment by klingtnet** [comment]
I've already added `arm=6` but you're maybe missing that the PKGBUILD uses builts from [github.com/klingtnet/caddy-release-downloader](https://github.com/klingtnet/caddy-release-downloader/releases).

**Comment by jannickfahlbusch** [comment]
I saw your changes already. 

Both comments after you closed the MR are delayed mails, because GH had problem with DynDNS. I'm going to delete them ;)

**Comment by jannickfahlbusch** [comment]
@klingtnet I opened https://github.com/klingtnet/caddy-release-downloader/pull/1 for final support of ARMv6. You use the ARM tarball for the ARMv6 binary instead of the ARMv6 one.

**Pull request closed without merging**
